Repository you-wanna-pc-of-me/rumble, pull requests merged in 2021-12, with the labels that each got.

#32 Task: Creating Readme.md file
  README.md
Labels: documentation

#33 Beginning React Native frameworks
  src/components/Navbar.tsx
  src/navigation/index.tsx
  src/screens/HomePageScreen.tsx
  src/screens/LogInScreen.tsx
  src/screens/RivalsListScreen.tsx
  src/screens/SignUpScreen.tsx
Labels: React Native

#39 (refactor): signupform - user's age, bio, and profileUrl now submit to Firestore
  package-lock.json
  src/screens/SignUpScreen.tsx
Labels: Firebase

#42 Refactor signup
  config/firebase.ts
  package-lock.json
  package.json
  src/screens/LogInScreen.tsx
  src/screens/SignUpScreen.tsx
Labels: bug, React Native, Firebase, Tier 1, TypeScript

#45 fix: style imports
  src/screens/SignUpScreen.tsx
Labels: bug

#46 Rival bios pop up & rival filtering
  src/components/Checkbox.tsx
  src/components/HomePage.style.ts
  src/screens/HomePageScreen.tsx
Labels: React Native, Tier 1

#47 Sign up firestore
  src/components/HomePage.style.ts
  src/components/Stylesheet.ts
  src/screens/LogInScreen.tsx
  src/screens/SignUpScreen.tsx
Labels: bug, enhancement

#51 Feat: NavBar Added
  App.tsx
  README.md
  package-lock.json
  package.json
  src/navigation/AppTabs.tsx
  src/navigation/index.tsx
  src/screens/LogInScreen.tsx
  src/screens/RivalsListScreen.tsx
Labels: React Native, Tier 1, TypeScript

#50 Profile firestore
  src/components/Stylesheet.ts
  src/screens/LogInScreen.tsx
  src/screens/SignUpScreen.tsx
  src/screens/UserProfileScreen.tsx
Labels: bug, React Native, Firebase, Tier 1, TypeScript

#54 Homepage firestore
  package-lock.json
  src/components/Stylesheet.ts
  src/screens/HomePageScreen.tsx
  src/screens/LogInScreen.tsx
  src/screens/UserProfileScreen.tsx
Labels: bug, enhancement, React Native, Firebase, Tier 1, TypeScript

#55 Matching
  src/screens/HomePageScreen.tsx
Labels: bug, React Native, Firebase, Fetch (API), Tier 1, TypeScript

#56 Profile
  package-lock.json
  src/components/Checkbox.tsx
  src/components/ProfileTabs.tsx
  src/screens/UserProfileScreen.tsx
Labels: bug, documentation, React Native, Firebase, Tier 1, TypeScript

#57 Homepage FIX
  src/screens/HomePageScreen.tsx
Labels: bug

#58 Rival filtering + matching
  src/screens/HomePageScreen.tsx
Labels: enhancement, React Native, Firebase, Tier 1, TypeScript

#60 Profile Refactoring
  src/components/ProfileTabs.tsx
  src/screens/SignUpScreen.tsx
  src/screens/UserProfileScreen.tsx
Labels: bug, enhancement, React Native, Firebase, Fetch (API), Tier 1, TypeScript

#61 Chat
  App.tsx
  package-lock.json
  package.json
  src/components/HomePage.style.ts
  src/screens/ChatScreen.tsx
  src/screens/RivalsListScreen.tsx
Labels: documentation, enhancement, Tier 1

#62 RivalsList, Home Page, and README updates
  README.md
  dfs
  src/navigation/index.tsx
  src/screens/ChatScreen.tsx
  src/screens/HomePageScreen.tsx
  src/screens/LogInScreen.tsx
  src/screens/RivalsListScreen.tsx
Labels: bug, documentation, React Native, Firebase, Tier 1, TypeScript

#63 Sign up
  assets/backgroundImage.png
  package-lock.json
  src/components/ProfileTabs.tsx
  src/components/Stylesheet.ts
  src/navigation/index.tsx
  src/screens/LoadingScreen.tsx
  src/screens/SignUpScreen.tsx
  src/screens/UserProfileScreen.tsx
Labels: bug, documentation, React Native, Firebase, Tier 1, TypeScript

#64 (Fix): Profile Settings LogOut Btn, able to click
  src/components/ProfileTabs.tsx
Labels: bug, React Native, Tier 1, TypeScript

#66 Images
  assets/backgroundImage 2.png
  assets/boxingheart.jpeg
  assets/cat.jpeg
  assets/ducky.jpeg
  src/components/Stylesheet.ts
  src/screens/SignUpScreen.tsx
Labels: enhancement

#67 (Fix): Images on SignUp & Loading Screen font
  src/components/Stylesheet.ts
  src/screens/SignUpScreen.tsx
Labels: bug, enhancement, React Native, Firebase

#69 (Fix): ScrollView on SignUp/ Rivals displays
  package-lock.json
  src/components/ProfileTabs.tsx
  src/components/Stylesheet.ts
  src/screens/SignUpScreen.tsx
  src/screens/UserProfileScreen.tsx
Labels: bug, React Native, Firebase, Tier 1, TypeScript

#71 Housekeeping
  package-lock.json
  src/components/Navbar.tsx
  src/navigation/index.tsx
  src/screens/HomePageScreen.tsx
  src/screens/LoadingScreen.tsx
  src/screens/LogInScreen.tsx
  src/screens/SignUpScreen.tsx
Labels: documentation, tidyCode

#72 Profile tabs
  src/components/ProfileTabs.tsx
  src/screens/UserProfileScreen.tsx
Labels: React Native, Firebase, Tier 1

#75 Rivals work
  src/screens/ChatScreen.tsx
  src/screens/RivalsListScreen.tsx
  src/screens/UserProfileScreen.tsx
Labels: bug

#76 Chatscreen
  package-lock.json
  src/screens/ChatScreen.tsx
  src/screens/RivalsListScreen.tsx
Labels: enhancement, Tier 1

#77 (Fix): Rendering a List of Rivals on Profile
  package-lock.json
  src/components/ProfileTabs.tsx
  src/screens/UserProfileScreen.tsx
Labels: bug, React Native, Firebase

#80 Housekeeping
  README.md
  assets/boxingheart.jpeg
  assets/cat.jpeg
  assets/chat.png
  assets/ducky.jpeg
  assets/favicon.png
  assets/home.png
  assets/logo.png
  dfs
  src/components/Stylesheet.ts
  src/screens/LogInScreen.tsx
  src/screens/SignUpScreen.tsx
Labels: bug, documentation, React Native, TypeScript, styled-components

#82 (Fix): some final bugs
  src/components/ProfileTabs.tsx
  src/screens/SignUpScreen.tsx
  src/screens/UserProfileScreen.tsx
Labels: bug
